version: '3.0'
services:
  streetmerchant:
    image: ghcr.io/jef/streetmerchant:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - dotenv
    port: 8080:8080
  autocaptcha:
    image: python:3.8-slim
    build:
      context: ./autocaptcha
      dockerfile: ./autocaptcha/Dockerfile
    container_name: flask/autocaptcha
    port: 8000:8000
